services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80" # Redirect to https
      - "8443:443" # Https
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/proxy.crt:/etc/nginx/proxy.crt:ro
      - ./proxy/proxy.key:/etc/nginx/proxy.key:ro
    depends_on:
      - music-api

  music-api:
    build:
      context: ./music_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=music_player_db
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: postgres:16
    container_name: music-player-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=music_player_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d music_player_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
